# Site settings
title: The Living God Church
email: tlgc777@gmail.com
url: http://www.tlg-church.com/
description: "Founded in 2009, the Church has seen spiritual and quantitative growth both in terms of membership maturity and numbers. TLG Churches now exist in 6 areas of the United Kingdom (Aberdeen, Basingstoke, Edinburgh, Glasgow, London, and Southampton) and in 3 areas of the Philippines (Sariaya-Quezon, Quezon City and Camiling-Tarlac).

We are praying for more churches to be planted in areas where the greatest spiritual needs are identified and where the Holy Spirit will lead us to go and make disciples of Jesus Christ."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#0b0a8a'
  links: '#1ca6c3'

# Footer settings
footer: The Living God Church

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
#  - title: twitter
#    url: https://twitter.com/
  - title: facebook
    url:  https://www.facebook.com/tlg.church.7
#  - title: stack-overflow
#    url: http://stackoverflow.com/
#  - title: bitbucket
#    url: http://bitbucket.org/
  - title: github
    url: https://github.com/tlgc

# Build settings
markdown: kramdown
permalink: pretty
